package com.model;
// Generated Apr 4, 2020 10:14:31 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product")
public class Product  implements java.io.Serializable {

@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)
@Column(name="ID_p")
     private Integer ID_p;

    public Integer getID_p() {
        return ID_p;
    }

    public void setID_p(Integer ID_p) {
        this.ID_p = ID_p;
    }
@Column(name="name")
     private String name;
@Column(name="charact")
    private String charact;
@Column(name="price")
     private double price;

    public Product() {
    }

    public Product(Integer  ID_p, String name, String charact, double price) {
        this. ID_p =  ID_p;
        this.name = name;
        this.charact = charact;
        this.price = price;
    }

    public Product(String name, String charact, double price) {
       this.name = name;
       this.charact = charact;
       this.price = price;
    }
   
    public Integer getID_P() {
        return this. ID_p;
    }
    
    public void setID_P(Integer  ID_p) {
        this. ID_p =  ID_p;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCharact() {
        return this.charact;
    }
    
    public void setCharact(String charact) {
        this.charact = charact;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


