package com.model;
// Generated Jun 3, 2020 6:22:08 PM by Hibernate Tools 4.3.1



/**
 * Characteristics generated by hbm2java
 */
public class Characteristics  implements java.io.Serializable {


     private Integer idCr;
     private Reservation reservation;
     private int guestN;
     private String requestT;

    public Characteristics() {
    }

    public Characteristics(Reservation reservation, int guestN, String requestT) {
       this.reservation = reservation;
       this.guestN = guestN;
       this.requestT = requestT;
    }
   
    public Integer getIdCr() {
        return this.idCr;
    }
    
    public void setIdCr(Integer idCr) {
        this.idCr = idCr;
    }
    public Reservation getReservation() {
        return this.reservation;
    }
    
    public void setReservation(Reservation reservation) {
        this.reservation = reservation;
    }
    public int getGuestN() {
        return this.guestN;
    }
    
    public void setGuestN(int guestN) {
        this.guestN = guestN;
    }
    public String getRequestT() {
        return this.requestT;
    }
    
    public void setRequestT(String requestT) {
        this.requestT = requestT;
    }




}


