package com.model;
// Generated Jun 3, 2020 6:22:08 PM by Hibernate Tools 4.3.1



/**
 * ClCp generated by hbm2java
 */
public class ClCp  implements java.io.Serializable {


     private Integer idLp;
     private ClientData clientData;
     private Reservation reservation;

    public ClCp() {
    }

    public ClCp(ClientData clientData, Reservation reservation) {
       this.clientData = clientData;
       this.reservation = reservation;
    }
   
    public Integer getIdLp() {
        return this.idLp;
    }
    
    public void setIdLp(Integer idLp) {
        this.idLp = idLp;
    }
    public ClientData getClientData() {
        return this.clientData;
    }
    
    public void setClientData(ClientData clientData) {
        this.clientData = clientData;
    }
    public Reservation getReservation() {
        return this.reservation;
    }
    
    public void setReservation(Reservation reservation) {
        this.reservation = reservation;
    }




}


