package com.model;
// Generated Jun 3, 2020 6:22:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientData generated by hbm2java
 */
public class ClientData  implements java.io.Serializable {


     private Integer idCd;
     private String FName;
     private String LName;
     private String cellPhone;
     private Set clCps = new HashSet(0);

    public ClientData() {
    }

	
    public ClientData(String FName, String LName, String cellPhone) {
        this.FName = FName;
        this.LName = LName;
        this.cellPhone = cellPhone;
    }
    public ClientData(String FName, String LName, String cellPhone, Set clCps) {
       this.FName = FName;
       this.LName = LName;
       this.cellPhone = cellPhone;
       this.clCps = clCps;
    }
   
    public Integer getIdCd() {
        return this.idCd;
    }
    
    public void setIdCd(Integer idCd) {
        this.idCd = idCd;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }
    public String getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }
    public Set getClCps() {
        return this.clCps;
    }
    
    public void setClCps(Set clCps) {
        this.clCps = clCps;
    }




}


