package com.model;
// Generated Jun 3, 2020 6:22:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer idR;
     private Date dateRes;
     private Date timeRes;
     private Set clCps = new HashSet(0);
     private Set characteristicses = new HashSet(0);

    public Reservation() {
    }

	
    public Reservation(Date dateRes, Date timeRes) {
        this.dateRes = dateRes;
        this.timeRes = timeRes;
    }
    public Reservation(Date dateRes, Date timeRes, Set clCps, Set characteristicses) {
       this.dateRes = dateRes;
       this.timeRes = timeRes;
       this.clCps = clCps;
       this.characteristicses = characteristicses;
    }
   
    public Integer getIdR() {
        return this.idR;
    }
    
    public void setIdR(Integer idR) {
        this.idR = idR;
    }
    public Date getDateRes() {
        return this.dateRes;
    }
    
    public void setDateRes(Date dateRes) {
        this.dateRes = dateRes;
    }
    public Date getTimeRes() {
        return this.timeRes;
    }
    
    public void setTimeRes(Date timeRes) {
        this.timeRes = timeRes;
    }
    public Set getClCps() {
        return this.clCps;
    }
    
    public void setClCps(Set clCps) {
        this.clCps = clCps;
    }
    public Set getCharacteristicses() {
        return this.characteristicses;
    }
    
    public void setCharacteristicses(Set characteristicses) {
        this.characteristicses = characteristicses;
    }




}


